// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHAflqmzZ0Yzj7-gKf9p7RlHDYdE1mB4',
    appId: '1:239455850641:web:8ea63f6f088b56a7306f30',
    messagingSenderId: '239455850641',
    projectId: 'hotel-management-68758',
    authDomain: 'hotel-management-68758.firebaseapp.com',
    storageBucket: 'hotel-management-68758.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoadhP3XuuQ8tppr_VLZN-CTlCgubFEjQ',
    appId: '1:239455850641:android:5f9bd7b50e5ba1d4306f30',
    messagingSenderId: '239455850641',
    projectId: 'hotel-management-68758',
    storageBucket: 'hotel-management-68758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA805M8v8F2mNtBAj0D49tbVypyJv3KBAQ',
    appId: '1:239455850641:ios:4e5a181fa4284669306f30',
    messagingSenderId: '239455850641',
    projectId: 'hotel-management-68758',
    storageBucket: 'hotel-management-68758.appspot.com',
    iosBundleId: 'com.example.hotelManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA805M8v8F2mNtBAj0D49tbVypyJv3KBAQ',
    appId: '1:239455850641:ios:af99433f5b26f8ad306f30',
    messagingSenderId: '239455850641',
    projectId: 'hotel-management-68758',
    storageBucket: 'hotel-management-68758.appspot.com',
    iosBundleId: 'com.example.hotelManagement.RunnerTests',
  );
}
